package com.dkdus.dementia.model.place_material
data class Items (
    var cnterNm:String?,
    var cnterSe:String?,
    var rdnmadr :String?,
    var lnmadr:String?,
    var latitude:String?,
    var longitude:String?,
    var fondYm : String?,
    var bildngAr : String?,
    var etcFclty : String?,
    var doctrCo : String?,
    var nurseCo: String?,
    var scrcsCo : String?,
    var etcHnfSttus : String?,
    var operInstitutionNm : String?,
    var rprsntvNm : String?,
    var operPhoneNumber : String?,
    var operCnsgnDate: String?,
    var imbcltyIntrcn : String?,
    var phoneNumber : String?,
    var institutionNm : String?,
    var referenceDate : String?,
    var insttCode :String?
    )
